### ISSUE TITLE
File not found - doesn't work

### ISSUE THREAD

**Issue by kirkas** [gruntjs/grunt-contrib-uglify#160]
Somehow, it seems that if you pass a invalid file url, it is automaticly stripped (silently). this is an issue because later in the code, when uglify will check if it exist, it will alway pass.

example:

```
vendor: {
    files: {
        "./dist/js/vendor.js': [
            "./src/components/jquery/dist/jquery/invalid-path.js",
            "./src/components/underscore/underscore.js",
            "./src/components/backbone/backbone.js"
        ]
    }
}
```

Then i pass a `grunt.log.warn(f.src)` in the uglify.js task, just after the `this.files.forEach` (grunt-contrib-uglify/tasks/uglify.js:63)

```
this.files.forEach(function(f) {
    grunt.log.warn(f.src);
    ...
```

**Grunt console output**

```
./src/components/underscore/underscore.js,./src/components/backbone/backbone.js
```

**Comment by jokeyrhyme** [comment]
Thanks @kirkas, [your comment](https://github.com/gruntjs/grunt-contrib-uglify/issues/160#issuecomment-35537793) is very important and needs to be read carefully. This is an especially sensitive feature.

Note that even with this setting, you only see console output when a file is missing. For example:

>Running "uglify" (uglify) task
>>> Source file blah.js not found.
>File foo.min.map created (source map).
>File foo.min.js created: 78.78 kB → 38.92 kB
>
>Done, without errors.

The exit code is still 0, so automated scripts have no idea that anything went wrong. Is it possible to fix this so that we get truly strict behaviour, and error exit codes when files are missing?

**Comment by joeldenning** [comment]
I know that this project and grunt itself aren't as popular anymore and that this might not be actively maintained anymore, but I would like to echo [@jokeyrhyme's comment](https://github.com/gruntjs/grunt-contrib-uglify/issues/160#issuecomment-72775083). We just deployed bad code to production at the company I work at because the exit code is zero even though a file isn't found in the build process (even when you use `nonull`). I think I will see if I can add that functionality to this project in a pr.
