### ISSUE TITLE
It's not recognizing "let" keyword, any plans to support it ?

### ISSUE THREAD

**Issue by sohansoni** [gruntjs/grunt-contrib-uglify#480]
It's not recognizing "let" keyword, any plans to support it ?

for e.g. my code is as below
`for (let key in item) {`

and error is as below:
`{ message: 'Unexpected token name «key», expected punc «;»',`

**Comment by alexlamsl** [comment]
`uglify-js` does not support ES6 - you will need `uglify-es` for that, which means using the `harmony` branch of this project:

https://github.com/gruntjs/grunt-contrib-uglify/tree/harmony

**Comment by sohansoni** [comment]
Thanks, Does uglify-es have backward compatibility for ES5 code as well ?

**Comment by alexlamsl** [comment]
Yes.

**Comment by sohansoni** [comment]
How do I get the harmony branch , because when I do `npm install grunt-contrib-uglify --save-dev` its giving me uglify-js instead of uglify-es ?

**Comment by chsyzxcv** [comment]
hi sohansoni,
do you find out how to install grunt-contrib-uglify harmony branch ? i am having the same issue as well..

**Comment by phoenixdev-kl** [comment]
Found it on https://stackoverflow.com/questions/44848273/how-to-integrate-uglify-es-in-grunt

`npm install git://github.com/gruntjs/grunt-contrib-uglify.git#harmony --save-dev`

If you are behind a firewall like me, please also notice https://github.com/npm/npm/issues/5257. The following worked fine for me:

```
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
```

**Comment by liquidvisual** [comment]
Thanks for this! Was searching for so long, I thought I was never going to find the answer. :)

**Comment by Kerwood** [comment]
When is `harmony` branch going to be `master`?
Its nice that we have the opportunity to download and use `uglify-es` manually, but it gives some challenges if your using a automated pipeline..

**Comment by samir-mahendra** [comment]
I have a weird issue with the "harmony" branch as of 3 days ago.  Two different functions are getting uglified into the exact same method name, which causes my code to break.

I found that this older commit from the "harmony" branch gets me back to where I was before:

npm install git://github.com/gruntjs/grunt-contrib-uglify.git#c2ccee1b61a585c5f4fca00da8f79cc1db37048b --save-dev

There is probably a more recent commit, but this worked, so I am using it for now.

If I have time, I'll try to put together a minimum reproducible test case.  I'm seeing it in an Angular JS project that uses this dependency: https://github.com/chieffancypants/angular-hotkeys.  At first I thought it was due to a change to angular-hotkeys, but then realized it only happened with the uglified code.

**Comment by liquidvisual** [comment]
I also experienced various errors with everything breaking suddenly, the following fixed it for me:

**package.json**
```
"grunt-contrib-uglify-es": "github:gruntjs/grunt-contrib-uglify#harmony",
```

**grunt.js**
```
grunt.loadNpmTasks('grunt-contrib-uglify-es');
```

**.babelrc**
```
{
	sourceType: 'script',
	  presets: [
	    ['env', {modules: false}],
	  ]
}
```

**Comment by induratized** [comment]
Use :
``` javascript
npm install terser
```
It's APIs are compatible with **UglifyJS@3** and supports `ES6+`

**Comment by AkashNeil** [comment]
I had a similar issue (i.e. not supporting ES6) and fixed it as follows:

`npm install grunt-contrib-uglify-es --save-dev`

**Comment by sitthykun** [comment]
Terser is adaptive to ES6+

> npm install terser
